---
- name: Install git
  become: true
  apt: name=git state=present

- name: Install GCC
  become: true
  apt: name=gcc state=present

- name: Create GOPATH directory
  file: path={{ hostvars[inventory_hostname].gopath }} state=directory
  when: GOPATH is undefined

- name: Create directory for SLAV
  file:
    path: "{{ hostvars[inventory_hostname].gopath }}/src/github.com/SamsungSLAV"
    state: directory

- name: Get Boruta src
  git:
    repo: 'https://github.com/SamsungSLAV/boruta'
    dest: "{{ hostvars[inventory_hostname].gopath }}/src/github.com/SamsungSLAV/boruta"
    version: 'v0.1.0'

- name: Get Weles src
  git:
    repo: 'https://github.com/SamsungSLAV/weles'
    dest: "{{ hostvars[inventory_hostname].gopath }}/src/github.com/SamsungSLAV/weles"
    version: 'v0.1.0'

- name: Get dependencies and install named packages
  command: /usr/local/go/bin/go get ./...
  args:
    chdir: "{{ hostvars[inventory_hostname].gopath }}/src/github.com/SamsungSLAV/weles"
