---
- name: Copy Weles server binary to /usr/local/bin
  become: yes
  copy:
    remote_src: yes
    src: "{{ hostvars[inventory_hostname].gopath }}/bin/weles-server"
    dest: /usr/local/bin/weles
    owner: root
    group: root
    mode: '0744'

- name: Add service file for Weles
  become: yes
  template:
    src: weles.service.j2
    dest: /etc/systemd/system/weles.service
    owner: root
    group: root
    mode: '0644'

- name: Enable and start Weles server
  become: yes
  systemd:
      daemon_reload: yes
      enabled: yes
      state: started
      name: weles
