---
- name: Create GOPATH directory
  file: path={{ hostvars[inventory_hostname].gopath }} state=directory
  when: GOPATH is undefined

- name: Create directory for SLAV
  file:
    path: "{{ hostvars[inventory_hostname].gopath }}/src/github.com/SamsungSLAV"
    state: directory
